### ISSUE TITLE
Move to fork-based development

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#574]
Currently we are all working on branches of the main gihub repo at PTB-MR. We want to transition to a workflow where everyone implements code on their own fork and then opens a PR to PTB-MR/mrpro. This will work for everything except changes to the docker files. These files can only be modified via PTB-MR/mrpro by a few people.

Steps to take:
- [x] Ensure github actions using docker images work: review and merge #555
- [ ] Modify contributor guide to highlight fork-based development
- [ ] Restrict write access
- [x] Fix comments of coverage and docs build for the public repos #585 
- [x] Add pre-commit hook to create notebooks also locally: adapt #537
   - [x] create/update notebook from script but do not change script from notebook
   - [x] add notebooks to git ignore and verify that does not create merge conflicts if notebooks are created locally, commit is pushed to origin and then git pull is called
- [x] Subfolders for notebooks and example scripts: probably done in #537 which closes #546
- [x] Add colab support to notebook; done in #537
- [x] Remove binder support and then close #538, close #457

Please try to do this in smaller PRs not in one go such that it is easier to review.
