### ISSUE TITLE
MRpro publication

### ISSUE THREAD

**Issue by ckolbPTB** [PTB-MR/mrpro#575]
(related to #410) Deadline End of Feb 2025

In the MRpro paper we would like to showcase:

1. Cartesian reconstruction with partial echo and partial Fourier #562
2. Pulseq feature
3. PDHG/FISTA reconstruction
4. qMRI

Paper outline:
- [x] Abstract
- [x] Introduction
- [x] Methods
   - [x] Software architecture (Dataclasses, Operators, Functionals, algorithms)
   - [x] Automatic reconstruction (from_kdata(), ISMRMRD/pulseq trajectories)
   - [x] Integration with DL
   - [ ] Quantitative imaging
   - [x] Community-based development and quality control (CI pipeline)
- [ ] Experiments/Results
   - [x] Cartesian recon - Christoph
   - [x] OpenRecon - Felix
   - [ ] TV GRPE - Christoph
   - [x] MODL - Felix
   - [x] TV unrolled - Andreas
   - [x] cMRF - Catarina
   - [x] PINQI - Felix
 - [ ] Discussion
   - [x] Difference to other packages (MONAI?) - Felix
   - [x] Why Pytorch specific and not e.g. cupy arrays?
 - [x] Conclusion

Potential figures:
- [ ] Code for simple reconstruction (multi echo, select first for csm) 
- ~[ ] flow chart for modular reconstruction of one example (read in data, dcf, csm, recon, dicom) - Johannes~
- [x] overview  - Felix
- [x] details of one reconstruction (proximal functional, Fourier op, Linear op), example of TV recon ~followed by fitting, link to maths~) - Andreas
- [x] CI flow chart of tests - David/Fellix/Leonid
- [x] Cartesian reco compared to scanner - Christoph #784 
- [x] open recon, Cartesian reco ~~ or WASABITI on T1MES~~ - Felix
- [x] MCIR GRPE Charité - Christoph #790
- [x] MODL - ||Ax - y|| - lambda ||x - xcnn|| using DifferentialOptimizerOp - Felix
- [x] TV unrolled, maybe use TV reco - Andreas #700 
- [x] cMRF - Catarina
- [x] PINQI - Felix

We still need:
- [x ] Differentiable Optimization Operators: Differentiable Optimization and Differentiable solver (only if it is straightforward)

- [x] NUFFT optimisation
   - [x] nufft op #463 
   - [x] speed-up by moving other-dimensions with same trajectory to batch
   - [x] evaluate finufft or pytorch-finufft #300 
   - [x] if faster add pytorch-finufft #646 
  
- [x] Indexing 
   - [x] #382 
   - [x] #298 
   - [x] #243 
   - [x]  move all data classes to ` *#other #coil #k2 #k1 #k0 ` shape
   - [x]  indexing for submitting: boolean indexing needs some thoughts: how to make kdata[idx.slice=1] keep stride-0/singletons
   - [x]  rearrange: almost done
 
- [ ] Writing data 
   - [ ] #401 
   - [x] #421
   - [x] exporting to dicom, test data available, similar to https://github.com/PTB-MR/mrpro/blob/f6692945811c5f710c8955082d2352e7c286424c/tests/data/_DicomTestImage.py#L17
   - [ ] exporting to nifti #702 

- [x] CI/CD
   - [x] fork development #574 
   - [x] #536
   - [x] #572
   - [x] run GPU tests automatically #785  
   - [x] Cuda tests for all operators #694

**Comment by fzimmermann89** [comment]
Code for simple reconstruction (multi echo, select first for csm)
-> we dont have this in our drft and maybe dont need it.
